# 应用名称
spring:
  application:
    name: paper-backend
  datasource:
    name: defaultDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blue?serverTimezone=UTC
    username: root
    password: 123456
  # 应用服务 WEB 访问端口
server:
  port: 8081
# es 服务地址
elasticsearch:
  host: 172.29.7.234
  # es 服务端口
  port: 9200

  # 配置日志级别,开启 debug 日志
logging:
  level:
    com:
      example:
        paper: debug

