spring:
  application:
    name: service-search
  elasticsearch:
    rest:
      uris: http://172.29.7.234:9200


server:
  port: 8081
# es 服务地址
elasticsearch:
  host: 172.29.7.234
  # es 服务端口
  port: 9200

  # 配置日志级别,开启 debug 日志
logging:
  level:
    com:
      example:
        paper: debug

